core/core/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls', namespace='home')),
    path('users/', include('user.urls', namespace='user')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/product/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'product'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('all-products/', products, name='products'),
    path('product/<int:pk>/', product, name='product'),
    path('buy/<int:pk>', buy, name='buy'),
    path('buy/shipping/', shipping, name='shipping'),
    path('categories/', categories, name='categories'),
    path('category/<int:pk>/products', category_p, name='category'),
    path('about-us/', about, name='about')
]

core/user/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'user'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('sign-up/', SignUp.as_view(), name='signup'),
    path('sign-in/', SignIn.as_view(), name='sign-in'),
    path('sign-out/', SignOut.as_view(), name='sign-out'),
    path('user-profile/', profile, name='profile'),
    path('user-change/', change, name='change'),
]

core/user/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    address = models.CharField(max_length=255, null=True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9}$')
    phone_number = models.CharField(validators=[phone_regex], max_length=9, blank=True, unique=True)  # validators should be a list
    avatar = models.ImageField(upload_to='user_imgs', blank=True, null=True)
    purchases = models.IntegerField(default=0)

core/user/forms.py
from django.contrib.auth.forms import UserCreationForm, UsernameField, AuthenticationForm
from django import forms
from .models import User


class SignUpForm(UserCreationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'class': 'form-control rounded-0', 'placeholder': 'Username'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control rounded-0',
                                                               'placeholder': 'Your name'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control rounded-0',
                                                              'placeholder': 'Your lastname'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control rounded-0',
                                                            'placeholder': 'Email'}))
    address = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control rounded-0',
                                                            'placeholder': 'Address to delivery'}))
    phone_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control rounded-0',
                                                                 'placeholder': 'Your phone number (507004522)'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control rounded-0',
                                                                  'placeholder': 'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control rounded-0',
                                                                  'placeholder': 'Password Again'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'address', 'phone_number')


class SignInForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control rounded-0',
                                                             'placeholder': 'Your username'}))
    password = forms.CharField(
        label="Passwodrd",
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control rounded-0', 'placeholder': 'Your password'}),
    )


class ChangeForm(forms.ModelForm):
    username = UsernameField(widget=forms.TextInput(attrs={'class': 'form-control rounded-0', 'placeholder': 'Username'}))
    avatar = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control rounded-0'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control rounded-0',
                                                               'placeholder': 'Your name'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control rounded-0',
                                                              'placeholder': 'Your lastname'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control rounded-0',
                                                            'placeholder': 'Email'}))
    address = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control rounded-0',
                                                            'placeholder': 'Address to delivery'}))
    phone_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control rounded-0',
                                                                 'placeholder': 'Your phone number (507004522)'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'address', 'phone_number')

core/user/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy, reverse
from django.views.generic.edit import CreateView, UpdateView
from django.shortcuts import render, redirect

from .forms import *
from .models import User


def profile(request):
    return render(request, 'user/profile.html')


@login_required
def change(request):
    if request.method == 'POST':
        form = ChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            img_obj = form.instance
            return render(request, 'user/profile.html', {'img_obj': img_obj })
    else:
        form = ChangeForm(instance=request.user)

    return render(request, 'user/change.html', {'form': form })


class Change(PermissionRequiredMixin, UpdateView):
    permission_required = ("is_staff",)
    model = User
    form_class = ChangeForm
    template_name = 'user/change.html'

    def get_queryset(self):
        return self.model.objects.filter(id=self.request.user.id)

    def get_success_url(self):
        return reverse('user:profile')


class SignUp(CreateView):
    template_name = 'user/signup.html'
    form_class = SignUpForm
    success_url = reverse_lazy('product:home')

    def get_queryset(self):
        return User.objects.all()


class SignIn(LoginView):
    form_class = SignInForm
    template_name = 'user/signin.html'


class SignOut(LogoutView):
    template_name = 'user/login.html'

core/user/templates/user/change.html
{% extends 'home.html' %}
{% load static %}
{% block image %}
{% endblock %}
{% block head %}
{% endblock %}
{% block content %}
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-5 p-5">
            <form enctype="multipart/form-data" method="post">
                <p>{{ form.errors }}</p>
                {{ form.as_p }}
                <div class="d-grid gap-2">
                <button type="submit" class="btn btn-dark rounded-0">Save</button>
                <a href="{% url 'user:profile' %}" class="btn btn-outline-secondary rounded-0">Cancel</a>
                </div>
                {% csrf_token %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

core/user/templates/user/profile.html
{% extends 'home.html' %}
{% load static %}
{% block image %}
{% endblock %}
{% block head %}
{% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="row mt-5">
        <div class="col-lg-4">
            {% if user.avatar %}
                <img class="img-fluid" src="{{ user.avatar.url }}" alt="">
            {% else %}
                <img class="img-fluid" src="{% static 'default/usr_img.png' %}" alt="">
            {% endif %}
        </div>
        <div class="col-lg-8">
            <p>Username: {{ user }}</p>
            <p>First name: {{ user.first_name }}</p>
            <p>Last name: {{ user.last_name }} </p>
            <p>Phone number: {{ user.phone_number|slice:'5' }}*** </p>
            <p>Address: {{ user.address|slice:'8' }}</p>
            <p>Date joined: {{ user.date_joined }}</p>
            <p>Email: {{ user.email|slice:'3' }}***</p>
        </div>
    </div>
    <div class="text-center">
        <a class="btn btn-outline-dark rounded-0" href="{% url 'user:change' %}">Change</a>
    </div>
</div>
{% endblock %}

core/user/templates/user/signin.html
{% extends 'home.html' %}
{% load static %}
{% block image %}
{% endblock %}
{% block head %}
{% endblock %}
{% block content %}
<div class="container mt-5 pt-5">
    <div class="row justify-content-md-center">
        <div class="col-4">
            <form method="post" action="{% url 'user:sign-in' %}">

                <p>{{ form.errors }}</p>
                {% for field in form %}
                <div class="form-group mb-3">
                    {{ field.label }}
                    {{ field }}
                    {{ field.help_text }}
                </div>
                {% endfor %}
                {% csrf_token %}
                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-block btn-dark mb-2 rounded-0" data-dismiss="modal">Sign In</button>
                    <a href="{% url 'product:home' %}" class="btn btn-block btn-outline-secondary rounded-0" data-dismiss="modal">
                        Cancel
                    </a>
                </div>
                <small>
                    <p class="text-center font-small">Don't have account?
                        <a href="{% url 'user:signup' %}" role="button">
                            Sign Up
                        </a>
                    </p>
                </small>
            </form>
        </div>
    </div>
</div>

{% endblock %}

core/user/templates/user/signup.html
{% extends 'home.html' %}
{% load static %}
{% block image %}
{% endblock %}
{% block head %}
{% endblock %}
{% block content %}
<div class="container mt-5 pt-5">
    <div class="row justify-content-md-center">
        <div class="col-4">
            <form method="post" action="{% url 'user:signup' %}">

                <p>{{ form.errors }}</p>
                {% for field in form %}
                <div class="form-group mb-3">
                    {{ field.label }}
                    {{ field }}
                    {{ field.help_text }}
                </div>
                {% endfor %}
                {% csrf_token %}
                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-block btn-dark mb-2 rounded-0" data-dismiss="modal">Sign up</button>
                    <a href="{% url 'product:home' %}" class="btn btn-block btn-outline-secondary rounded-0" data-dismiss="modal">
                        Cancel
                    </a>
                </div>
                <small>
                    <p class="text-center font-small">Already have account?
                        <a href="" role="button">
                            Sign In
                        </a>
                    </p>
                </small>
            </form>
        </div>
    </div>
</div>

{% endblock %}