core/core/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls', namespace='home')),
    path('users/', include('user.urls', namespace='user')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/product/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'product'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('all-products/', products, name='products'),
    path('product/<int:pk>/', product, name='product'),
    path('buy/<int:pk>', buy, name='buy'),
    path('buy/shipping/', shipping, name='shipping'),
    path('categories/', categories, name='categories'),
    path('category/<int:pk>/products', category_p, name='category'),
    path('about-us/', about, name='about')
]

core/user/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'user'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('sign-up/', SignUp.as_view(), name='signup'),
    path('sign-in/', SignIn.as_view(), name='sign-in'),
    path('sign-out/', SignOut.as_view(), name='sign-out'),
    path('user-profile/', profile, name='profile'),
    path('user-change/', change, name='change'),
]

core/product/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    title = models.CharField(max_length=100, blank=False)
    description = models.CharField(max_length=255, blank=True)

    def get_absolute_url(self):
        return reverse('product:category', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class Product(models.Model):
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='products')
    title = models.CharField(max_length=100, blank=False)
    price = models.IntegerField(null=False, blank=False)
    description = models.TextField(null=False, blank=False)
    date = models.DateField(auto_now=True)
    available = models.BooleanField(default=True)
    featured = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('product:product', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class Gallery(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='product_img', blank=True)

    def __str__(self):
        return self.product.title


class Sells(models.Model):
    product_n = models.CharField(max_length=100, blank=False)
    amount = models.IntegerField(null=False, blank=False)
    total_p = models.IntegerField(null=False, blank=False)
    shipping_a = models.CharField(max_length=100, blank=False)
    client_n = models.CharField(max_length=100, blank=False)
    client_p = models.CharField(max_length=100, blank=False)

    def __str__(self):
        return self.product_n + ' ' +self.client_n

core/product/views.py
from django.shortcuts import render
from .models import *


def home(request):
    f_products = Product.objects.filter(featured=True)
    return render(request, 'home.html', {'f_products': f_products})


def products(request):
    all_products = Product.objects.all()
    return render(request, 'product/products.html', {'products': all_products})


def product(request, pk):
    o_product = Product.objects.get(id=pk)
    return render(request, 'product/product.html', {'product': o_product})


def buy(request, pk):
    user = request.user
    o_product = Product.objects.get(id=pk)
    return render(request, 'product/buy.html', {'product': o_product, 'user': user})


def shipping(request):
    if request.method == 'POST':
        msg = 'Thanks! soon admins will write to you for details'
        user = request.user
        form = request.POST
        product_n = form.get('p_title')
        amount = int(form.get('amount'))
        price = int(form.get('p_price'))
        shipping_a = user.address
        Sells.objects.create(product_n=product_n, amount=amount, total_p=amount*price,
                             shipping_a=shipping_a, client_n=user, client_p=user.phone_number)
    else:
        return reverse('product:products')
    return render(request, 'product/success.html', {'msg':msg})


def categories(request):
    all_categories = Category.objects.all()
    return render(request, 'product/categories.html', {'categories': all_categories})


def category_p(request, pk):
    category = Category.objects.get(id=pk)
    return render(request, 'product/c_products.html', {'category': category})


def about(request):
    return render(request, 'product/about.html')

core/product/templates/product/about.html
{% extends 'home.html' %}
{% load static %}
{% block image %}
{% endblock %}
{% block head %}
{% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="row border justify-content-md-center mt-5 p-3 fw-bold isoct">
        <div class="col-12 text-center m-2"><h3>OUR DEVELOPERS</h3></div>
        <div class="col-6">
            <div class="card border-dark mb-3 rounded-0" >
                <div class="card-header border-dark">Eldiiar Abdyldev</div>
                <img src="{% static 'default/eldiiar.jpg' %}" class="card-img-top" alt="..." style="height:380px">
                <div class="card-body text-dark">
                    <h5 class="card-title">Ala-Too COM 20-A</h5>
                    <p class="card-text">
                        <a href="https://github.com/eldiyar01/" class="nav-link text-dark">Github</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card border-dark mb-3 rounded-0" >
                <div class="card-header border-dark">Saadilaaev Erkin</div>
                <img src="{% static 'default/erkin.jpg' %}" class="card-img-top" alt="..." style="height:380px">
                <div class="card-body text-dark">
                    <h5 class="card-title">Ala-Too COM 20-A</h5>
                    <p class="card-text">
                        <a href="https://github.com/ballboypro/" class="nav-link text-dark">Github</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

core/product/templates/product/buy.html
{% extends 'home.html' %}
{% load static %}
{% block image %}
{% endblock %}
{% block head %}
{% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="row justify-content-md-center mt-5">
        <div class="col-6 border p-3">
            <form action="{% url 'product:shipping' %}" method="post">
                <table class="table table-hover table-dark ">
                    <tbody>
                    <tr>
                        <th scope="row">For:</th>
                        <td>{{user}}</td>
                    </tr>
                    <tr>
                        <th scope="row">Shipping address:</th>
                        <td>{{user.address}}</td>
                    </tr>
                    <tr>
                        <th scope="row">Product:</th>
                        <td><input type="text" name="p_title" hidden value="{{product.title}}">{{product.title}}</td>

                    </tr>
                    <tr>
                        <th scope="row">Price:</th>
                        <td><input type="number" name="p_price"  hidden value="{{product.price}}">{{product.price}}$</td>
                    </tr>
                    </tbody>
                </table>
                <hr>
                <div>Amount:<input name="amount" class="m-1 col-1" type="number" value="1"></div>
                <div class="d-grid gap-2">
                    <button class="btn btn-sm btn-outline-success rounded-0" type="submit">BUY</button>
                </div>
                {% csrf_token %}
            </form>
        </div>
    </div>
</div>

{% endblock %}

core/product/templates/product/c_products.html
{% extends 'home.html' %}
{% load static %}
{% block image %}
{% endblock %}
{% block head %}
{% endblock %}
{% block content %}
<div class="mt-5 text-center pt-5">
    <hr>
    <h3 class="isoct fw-bold"> {{category.title}} </h3>
    <hr>
</div>
{% for product in category.products.all %}
        <div class="col-4 mt-5">
            <div class="card rounded-0">
              <img src="{{ product.images.first.image.url }}" class="card-img-top rounded-0" style="height:300px" alt="...">
              <div class="card-body">
                <p class="card-text">{{ product.description|slice:120 }} ...</p>
              </div>
            </div>
            <div class="text-center mt-4">
                <a href="{{ product.get_absolute_url }}" class="btn btn-lg btn-outline-dark rounded-0">Check it</a>
            </div>
        </div>
        {% endfor %}
{% endblock %}

core/product/templates/product/categories.html
{% extends 'home.html' %}
{% load static %}
{% block image %}
{% endblock %}
{% block content %}
        {% for category in categories %}
            <div class="d-grid m-1">
              <a class="btn btn-outline-dark rounded-0" href="{{ category.get_absolute_url }}">{{ category.title }}</a>
            </div>
        {% endfor %}
{% endblock %}

core/product/templates/product/product.html
{% extends 'home.html' %}
{% load static %}
{% block image %}
{% endblock %}
{% block head %}
{% endblock %}
{% block content %}
<div class="m-5"></div>
<div class="col-5">
    <div id="carousel" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{{ product.images.first.image.url }}" class="d-block w-100" alt="...">
            </div>
            {% for product_img in product.images.all|slice:'1:' %}
            <div class="carousel-item">
                <img src="{{ product_img.image.url }}" class="d-block w-100" alt="...">
            </div>
            {% endfor %}
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
        </button>
    </div>

</div>
<div class="col-7">
    <strong>{{ product.title }}</strong>
    <hr>
    <p><strong>Price:</strong> ${{ product.price }}</p>
    {% if product.available %}
        <p class="text-success">Available</p>
    {% else %}
        <p class="text-danger">Unavailable</p>
    {% endif %}
    <strong>About this item:</strong>
    <br>
    {{ product.description }}
    <hr>
    {% if user.is_authenticated %}

        <a href="{% url 'product:buy' product.pk %}" class="btn btn-outline-success rounded-0">Buy</a>
    {% else %}
        <a href="{% url 'user:sign-in' %}" class="btn btn-outline-success rounded-0">Buy</a>
    {% endif %}
</div>
{% endblock %}

core/product/templates/product/products.html
{% extends 'home.html' %}
{% load static %}
{% block image %}
<div id="carousel" class="carousel slide" data-bs-ride="false">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
  </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{% static 'default/carousel1.png' %}" class="d-block w-100"  alt="...">
            <div class="carousel-caption d-none d-md-block isoct fw-bold">
                <h4 class="fw-bold text-dark txt-sh">We made everything with love</h4>
                <br>
                {% if user.is_authenticated %}
                <p class="fw-bold text-dark txt-sh"> Welcome! We hope you will be satisfied</p>
                {% else %}
                <a class="btn btn-sm btn-dark rounded-0 fw-bold" aria-current="page" href="{% url 'user:signup' %}">
                    Sign Up
                </a>
                <a class="btn btn-sm btn-dark rounded-0 fw-bold" aria-current="page" href="{% url 'user:sign-in' %}">
                    Sign In
                </a>
                {% endif %}
            </div>
        </div>
            <div class="carousel-item">
                <img src="{% static 'default/carousel2.jpeg' %}" class="d-block w-100"  alt="...">
            <div class="carousel-caption d-none d-md-block isoct fw-bold">
                <h4 class="fw-bold text-dark txt-sh">We made everything with love</h4>
                <br>
                {% if user.is_authenticated %}
                <p class="fw-bold text-dark txt-sh"> Welcome! We hope you will be satisfied</p>
                {% else %}
                <a class="btn btn-sm btn-dark rounded-0 fw-bold" aria-current="page" href="{% url 'user:signup' %}">
                    Sign Up
                </a>
                <a class="btn btn-sm btn-dark rounded-0 fw-bold" aria-current="page" href="{% url 'user:sign-in' %}">
                    Sign In
                </a>
                {% endif %}
            </div>
        </div>
    </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carousel" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carousel" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>

</div>
{% endblock %}
{% block content %}
{% for product in products %}
<div class="col-4 mt-5">
    <div class="card rounded-0">
      <img src="{{ product.images.first.image.url }}" class="card-img-top rounded-0" style="height:300px" alt="...">
      <div class="card-body">
        <p class="card-text">{{ product.description|slice:120 }} ...</p>
      </div>
    </div>
    <div class="text-center mt-4">
        <a href="{{ product.get_absolute_url }}" class="btn btn-lg btn-outline-dark rounded-0">Check it</a>
    </div>
</div>
{% endfor %}
{% endblock %}

core/product/templates/product/success.html
{% extends 'home.html' %}
{% load static %}
{% block image %}
{% endblock %}
{% block head %}
{% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="row justify-content-md-center mt-5">
        <div class="col-6 border p-3 isoct">
            {% if msg %}
                <div class="card rounded-0 card border-dark">
                    <div class="card-body text-center ">
                        <h3 class="fw-bold">{{msg}}</h3>
                    </div>
                </div>
            <div class="d-grid gap-2">
                <a class="btn btn-outline-dark rounded-0 fw-bold mt-3" href="{% url 'product:products' %}">Continue</a>
             </div>
            {% else %}
            <div class="d-grid gap-2">
                <a class="btn btn-outline-dark rounded-0 fw-bold mt-3" href="{% url 'product:products' %}">All products</a>
             </div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}