core/core/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls', namespace='home')),
    path('users/', include('user.urls', namespace='user')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/product/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'product'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('all-products/', products, name='products'),
    path('product/<int:pk>/', product, name='product'),
    path('buy/<int:pk>', buy, name='buy'),
    path('buy/shipping/', shipping, name='shipping'),
    path('categories/', categories, name='categories'),
    path('category/<int:pk>/products', category_p, name='category'),
    path('about-us/', about, name='about')
]

core/user/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'user'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('sign-up/', SignUp.as_view(), name='signup'),
    path('sign-in/', SignIn.as_view(), name='sign-in'),
    path('sign-out/', SignOut.as_view(), name='sign-out'),
    path('user-profile/', profile, name='profile'),
    path('user-change/', change, name='change'),
]

core/templates/home.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Heko</title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
    <link href="{% static 'default/styles.css' %}" rel="stylesheet" type="text/css" media="all" />
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
</head>
<body class="">
<nav class="navbar bg-dark p-2 fixed-top">

    <a class="nav-link active text-white isoct fw-bold" aria-current="page" href="{% url 'product:home' %}">Heko</a>
    {% if user.is_authenticated and user.avatar %}
        <a class="profile" href="{% url 'user:profile' %}">
            <img class="rounded-circle sm-profile"  src="{{ user.avatar.url }}" alt="">
        </a>
        <a class="btn btn-sm btn-outline-light rounded-0" aria-current="page" href="{% url 'user:sign-out' %}">Sign Out</a>
    {% elif user.is_authenticated %}
        <a class="profile" href="{% url 'user:profile' %}">
            <img class="img-rounded sm-profile" src="{% static 'default/usr_img.png' %}" alt="">
        </a>
        <a class="btn btn-sm btn-outline-light rounded-0" aria-current="page" href="{% url 'user:sign-out' %}">Sign Out</a>
    {% else %}
        <a class="btn btn-sm btn-outline-light rounded-0" aria-current="page" href="{% url 'user:signup' %}">Shopping</a>
    {% endif %}
</nav>
<div></div>
{% block image %}

<div id="carousel" class="carousel slide" data-bs-ride="false">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{% static 'default/bg.png' %}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block isoct fw-bold">
                <h4 class="fw-bold">Start shopping</h4>
                <br>
                {% if user.is_authenticated %}
                <p> Welcome! We hope you will be satisfied</p>
                {% else %}
                <a class="btn btn-sm btn-outline-light rounded-0 fw-bold" aria-current="page" href="{% url 'user:signup' %}">
                    Sign Up
                </a>
                <a class="btn btn-sm btn-outline-light rounded-0 fw-bold" aria-current="page" href="{% url 'user:sign-in' %}">
                    Sign In
                </a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}
<ul class="nav bg-dark2 justify-content-center isoct fw-bold p-2 sticky-top sticky-offset">
    <li class="nav-item">
        <a class="nav-link active text-white" aria-current="page" href="{% url 'product:home' %}">HOME</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'product:categories' %}">CATEGORIES</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'product:products' %}">ALL</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'product:about' %}">ABOUT US</a>
    </li>
</ul>
{% block head %}
<h1 class="text-center isoct fw-bold mt-4 p-3">UNIQUE HANDMADE HOME DECORATIONS</h1>
<h3 class="text-center isoct fw-bold p-2">Check it below</h3>
<img src="{% static 'default/sl.png' %}" class="w-50 mx-auto d-block" alt="...">
{% endblock %}

<div class="container pb-5 mb-5 ml-5">
    <div class="row mb-5">
    {% block content %}
        {% for product in f_products %}
        <div class="col-4 mt-5">
            <div class="card rounded-0">
              <img src="{{ product.images.first.image.url }}" class="card-img-top rounded-0" style="height:300px" alt="...">
              <div class="card-body">
                <p class="card-text">{{ product.description|slice:120 }} ...</p>
              </div>
            </div>
            <div class="text-center mt-4">
                <a href="{{ product.get_absolute_url }}" class="btn btn-lg btn-outline-dark rounded-0">Check it</a>
            </div>
        </div>
        {% endfor %}
        <hr class="mt-5">
        <div class="text-center mt-4">
            <a href="{% url 'product:products' %}" class="btn btn-lg btn-outline-dark rounded-0">M O R E</a>
        </div>
    {% endblock %}
    </div>
</div>
</body>
<footer class="footer">
  <p>&copy; Heko company 2021-2022 by students <img class="rounded-circle sm-profile"  src="{% static 'default/logo.png' %}" alt=""></p>
</footer>
</html>